injection_method: clean
attack_tool:
  # - all
  # - agg
  # - non-agg
  - test
write_db: false # true,false

llms:
  - gpt-4o-mini
  - gpt-3.5-turbo
  - gpt-4o-2024-08-06
  - claude-3-5-sonnet-20240620
  - ollama/gemma2:27b
  - ollama/llama3:70b
  - ollama/llama3.1:70b
  # - ollama/qwen2:72b
  # - ollama/qwen2:7b
  # - ollama/gemma2:9b
  # - ollama/mixtral:8x7b
  # - ollama/llama3:8b
  # - ollama/llama3.1:8b

attack_types:
  - combined_attack


defense_type: instructional_prevention # delimiters_defense, direct_paraphrase_defense, instructional_prevention, dynamic_prompt_rewriting
suffix: args
