injection_method:
  - cot_backdoor
  # - cot_clean
  # - clean
attack_tool:
  - all
  # - agg
  # - non-agg
llms:
  - gpt-4o-mini
  # - gpt-3.5-turbo
  # - gpt-4o-2024-08-06
  # - claude-3-5-sonnet-20240620
  # - ollama/qwen2:72b
  # - ollama/qwen2:7b
  # - ollama/gemma2:9b
  # - ollama/gemma2:27b
  # - ollama/llama3:70b
  # - ollama/llama3.1:70b
  # - ollama/mixtral:8x7b
  # - ollama/llama3:8b
  # - ollama/llama3.1:8b

attack_types:
  - naive

triggers:
  - with perspicacious discernment
  # - through a prism of insight
  # - conducting a comprehensive elucidation
  # - ':)'
  # - '@_@'

task_num: 2
# defense_type: cot_shuffling_defense # cot_paraphrase_defense, cot_shuffling_defense
# suffix: test
